# Generated by Django 4.2.5 on 2023-09-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='تصویر محصول')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('category', models.ManyToManyField(related_name='products', to='Product_module.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
