# Generated by Django 4.2.5 on 2023-09-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='سایز عینک')),
                ('color', models.CharField(max_length=20, verbose_name='رنگ عینک')),
                ('shape', models.CharField(max_length=20, verbose_name='شکل عینک')),
                ('type', models.CharField(max_length=20, verbose_name='نوع عینک')),
                ('material', models.CharField(max_length=20, verbose_name='جنس عینک')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
    ]
