# Generated by Django 4.2.5 on 2023-09-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0003_alter_product_image_alter_product_slug_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی اصلی',
                'verbose_name_plural': 'دسته بندی های اصلی',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent_category',
            field=models.ManyToManyField(related_name='parentcategory', to='Product_module.productparentcategory'),
        ),
    ]
