# Generated by Django 4.2.5 on 2023-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0004_productparentcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category', to='Product_module.productcategory', verbose_name='دسته بندی'),
        ),
    ]
