# Generated by Django 4.2.5 on 2023-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='category', to='Product_module.productcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.ManyToManyField(db_index=True, related_name='parentcategory', to='Product_module.productparentcategory'),
        ),
    ]
