# Generated by Django 4.2.5 on 2023-09-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0007_remove_product_slug_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='عنوان ویژگی')),
            ],
            options={
                'verbose_name': 'عنوان ویژگی',
                'verbose_name_plural': 'عنوان ویژگی ها',
            },
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='type',
        ),
        migrations.AddField(
            model_name='productoption',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مقدار ویژگی'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='option_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_module.optionfield', verbose_name='عنوان ویژگی'),
        ),
    ]
