# Generated by Django 4.2.5 on 2023-09-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0008_optionfield_alter_productoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionfield',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_module.productparentcategory', verbose_name='دسته بندی مربوطه'),
        ),
    ]
