# Generated by Django 4.2.5 on 2023-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0009_optionfield_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionfield',
            name='category',
        ),
        migrations.AddField(
            model_name='optionfield',
            name='category',
            field=models.ManyToManyField(null=True, to='Product_module.productparentcategory', verbose_name='دسته بندی مربوطه'),
        ),
    ]
