# Generated by Django 4.2.5 on 2023-09-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0010_remove_optionfield_category_optionfield_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_field', to='Product_module.optionfield', verbose_name='عنوان ویژگی'),
        ),
    ]
