# Generated by Django 4.2.5 on 2023-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0011_alter_productoption_option_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده / نشده'),
        ),
    ]
