# Generated by Django 4.2.5 on 2023-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0012_alter_productcategory_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Purchase_guide',
            field=models.TextField(default='برای اطلاعات بیشتر تماس بگیرید', verbose_name='روش خرید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت'),
        ),
    ]
