# Generated by Django 4.2.5 on 2023-12-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0013_product_purchase_guide_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Purchase_guide',
            new_name='purchase_guide',
        ),
    ]
