# Generated by Django 4.2.5 on 2023-09-05 18:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک های فوتر',
                'verbose_name_plural': 'دسته بندی های لینک های فوتر',
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_url',
            field=models.CharField(max_length=200, validators=[django.core.validators.URLValidator()], verbose_name='دامنه سایت'),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='لینک')),
                ('footerbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_module.footerbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
    ]
