# Generated by Django 4.2.5 on 2023-09-06 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0002_footerbox_alter_sitesetting_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن بنر')),
                ('btn_title', models.CharField(max_length=50, verbose_name='عنوان دکمه')),
                ('btn_url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='لینک دکمه')),
            ],
            options={
                'verbose_name': 'بنر اصلی',
            },
        ),
    ]
