# Generated by Django 4.2.5 on 2023-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0005_mainbanner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
