# Generated by Django 4.2.5 on 2023-09-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0006_alter_mainbanner_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'بنر اصلی', 'verbose_name_plural': 'بنر اصلی'},
        ),
    ]
