# Generated by Django 4.2.5 on 2023-09-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0008_optionfield_alter_productoption_options_and_more'),
        ('Home_module', '0007_alter_mainbanner_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbanner',
            name='text',
        ),
        migrations.RemoveField(
            model_name='mainbanner',
            name='title',
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_cat', to='Product_module.productparentcategory'),
        ),
    ]
