# Generated by Django 4.2.5 on 2023-09-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0008_remove_mainbanner_text_remove_mainbanner_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار عنوان فوتر')),
                ('footerlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_module.footerlink', verbose_name='عنوان فوتر')),
            ],
            options={
                'verbose_name': 'مقدار فوتر',
                'verbose_name_plural': 'مقدار های فوتر',
            },
        ),
    ]
