# Generated by Django 4.2.5 on 2023-09-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0009_footerlinkvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slides',
            name='text',
        ),
    ]
