# Generated by Django 4.2.5 on 2023-09-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0013_product_purchase_guide_alter_product_price'),
        ('Home_module', '0011_slides_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedProoductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/suggustion', verbose_name='تصویر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_module.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول پیشنهادی',
                'verbose_name_plural': 'محصولات پیشنهادی',
            },
        ),
    ]
