# Generated by Django 4.2.5 on 2023-11-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_module', '0013_product_purchase_guide_alter_product_price'),
        ('Home_module', '0014_alter_suggestedprooductsection_parent_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuggestedProoductSection',
            new_name='SuggestedProductSection',
        ),
    ]
